name = "gcto"
main = "src/index.ts"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

preview_urls = false

## KV namespaces are injected at build/dev time.
## Do not define kv_namespaces here to allow `wrangler kv namespace create` to run without validation errors.

# [vars]


# --- Local Development Configuration ---
# This section configures local development with Docker and miniflare
[dev]
ip = "0.0.0.0"          # Bind to all interfaces for Docker access
port = 8787             # Port for local development server
# Note: --persist-to flag in Docker handles storage location

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
