name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Generate wrangler config
        run: node scripts/prepare-wrangler-config.mjs
        env:
          # Inject KV ID from repository secret (set in Settings → Secrets)
          GEMINI_CLI_KV_ID: ${{ secrets.GEMINI_CLI_KV_ID }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Use generated config to avoid exposing KV ID in repo
          command: deploy --config .wrangler.generated.toml
